export const ActionTypes = {
    FETCH_USERS_REQUEST : 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS : 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE : 'FETCH_USERS_FAILURE',
    EDIT_USER_REQUEST : 'EDIT_USER_REQUEST',
    EDIT_USER_SUCCESS : 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILURE : 'EDIT_USER_FAILURE',
}

export default ActionTypes;